general:
  folder_output: ../../../../data/co-design/reference/
  fname_output: reference

recorder:
  flag: true
  file_name: reference.sql
  includes: ["aeroelastic.*", "tune_rosco_ivc.*"]  # Just "*" doesn't work due to some non-uniqueness problem.
