general:
  folder_output: ../../data/design_of_experiments/ps_vs_ipc_all_sweep/
  fname_output: ps_vs_ipc_all_sweep

design_variables:
  control:
    # ps_percent:
    #   flag: true
    #   lower_bound: 0.5
    #   upper_bound: 1.0

    servo:
      tcipc_control:
        TCIPC_MaxTipDeflection:
          flag: true
          min: 0.0
          max: 20.0
        # TCIPC_nHarmonics:
        #   flag: true
        #   min: 1
        #   max: 10
        TCIPC_ZeroYawDeflection:
          flag: true
          min: 0
          max: 1

# merit_figure: AEP  # Only uses WISDEM I think.
merit_figure_user: 
  name: aeroelastic.AEP
  ref: 81000000
  max_flag: true

driver:
  design_of_experiments:
    flag: true
    run_parallel: true
    generator: FullFact
    num_samples: 2  # For FullFact, this is not the amount of samples, but amount of levels.

recorder:
  flag: true
  file_name: log_ps_vs_ipc_all_sweep.sql
  includes: ["aeroelastic.*", "tune_rosco_ivc.*"]  # Just "*" doesn't work due to some non-uniqueness problem.
