general:
  folder_output: ../../data/optimal_tuning/maxTipDxc_10/
  fname_output: maxTipDxc_10

design_variables:
  control:
    ps_percent:
      flag: true
      lower_bound: 0.6
      upper_bound: 1.0

    servo:
      tcipc_control:
        TCIPC_MaxTipDeflection:
          flag: true
          min: 0.0
          max: 20.0

constraints:
  user:
    - name: aeroelastic.max_TipDxc_towerPassing
      upper_bound: [10.0]

# merit_figure: AEP  # Only uses WISDEM I think.
merit_figure_user: 
  name: aeroelastic.AEP
  ref: 81000000
  max_flag: true

driver:
  optimization:
    flag: true
    tol: 0.001
    max_iter: 75
    solver: "LN_COBYLA"  # COBYLA didn't adhere to the bounds of the design variables for me...

recorder:
  flag: true
  file_name: log_maxTipDxc_10.sql
