general:
  folder_output: ../../../../data/optimal_tuning/check_DLCs/
  fname_output: check_DLCs

recorder:
  flag: true
  file_name: log_check_DLCs.sql
  includes: ["aeroelastic.*", "tune_rosco_ivc.*"]  # Just "*" doesn't work due to some non-uniqueness problem.
