general:
  folder_output: ../../../../data/torque/laminar/
  fname_output: laminar

design_variables:
  control:
    servo:
      tcipc_control:
        TCIPC_MaxTipDeflection:
          flag: true
          min: 10.0
          max: 20.0
        TCIPC_ZeroYawDeflection:
          flag: true
          min: 0
          max: 1

# merit_figure: AEP  # Only uses WISDEM I think.
merit_figure_user: 
  name: aeroelastic.AEP
  ref: 81000000
  max_flag: true

driver:
  design_of_experiments:
    flag: true
    run_parallel: true
    generator: FullFact
    num_samples: 2  # For FullFact, this is not the amount of samples, but amount of levels.

recorder:
  flag: true
  file_name: log_laminar.sql
  includes: ["aeroelastic.*", "tune_rosco_ivc.*"]  # Just "*" doesn't work due to some non-uniqueness problem.
